# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Actions Exapmple with Maven

on:
  schedule: 
    - cron:  0,0 21 * * *
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Saravanan Github Actions Test
      env: 
        suiteName: "regression.xml"  
      run: echo ${suiteName}
